name: smart_home_app
description: 
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  provider: ^6.1.5+1
  go_router: ^16.2.5
  multicast_dns: 0.3.2+6

  path: ^1.9.1
  path_provider: ^2.1.5

  smart_home_core:
    path: ../smart_home_core

  air_quality:
    path: ../air_quality

  smart_leds:
    path: ../smart_leds

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/air_quality/
    - assets/smart_leds/
