; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@6.11.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv
board_build.filesystem = littlefs

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/adafruit/Adafruit_NeoPixel.git
  https://github.com/adafruit/Adafruit_BME280_Library.git
	https://github.com/SolderedElectronics/Soldered-SHTC3-Temperature-Humidity-Sensor-Arduino-Library.git
	https://github.com/jmojzes21/Soldered-PCF85063A-RTC-Module-Arduino-Library.git
  