name: smart_leds
description: 
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  http: ^1.2.0
  crypto: ^3.0.3
  path_provider: ^2.1.2
  file_selector: ^1.0.3
  async: ^2.11.0
  multicast_dns: 0.3.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
