quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:port/database_name
quarkus.hibernate-orm.log.sql=true
