name: smart_home_app
description: 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  
  smart_home_core:
    path: ../smart_home_core

  air_quality:
    path: ../air_quality

  smart_leds:
    path: ../smart_leds

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/air_quality/
    - assets/smart_leds/
